[package]
name = "carbon-okx-dex-decoder"
version = "0.5.1"
description = "OKX DEX Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = "0.9.1"
serde = { version = "1.0.208", features = ["derive"] }
solana-sdk = "2.2.1"
